server:
  port: 9105
spring:
  application:
    name: gateway-server
  security:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:9696/auth/realms/ecommerce


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
