server:
  port: 9105
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://loca*****:****"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      routes:
        - id: commandeModule
          uri: lb://microservice-commandes
          predicates:
            - Path=/commandes/**

        - id: produitModule
          uri: lb://microservice-produits
          predicates:
            - Path=/produits/**

        - id: paiements
          uri: lb://microservice-paiements
          predicates:
            - Path=/paiements/**




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
