

# Configurations H2
spring:
  security:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:9696/auth/realms/ecommerce
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

#Config
configs:
  maxProduits: 2