

# Configurations H2
spring:
  application.name: microservice-produits
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9696/auth/realms/ecommerce
          jwks_uri: http://localhost:9696/auth/realms/ecommerce/protocol/openid-connect/certs
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

#Config
configs:
  maxProduits: 2