

# Configurations H2
spring:
  security:
    oauth2:
      resourceserver: http://localhost:9696/auth/realms/ecommerce

  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

#Config
configs:
  maxProduits: 2